---

- name: check if user is in subuid file
  shell: "grep -i '^{{ container_run_as_user}}:.*' /etc/subuid"
  register: uid_line_found
  when: container_run_as_user != 'root'

- name: check if group is in subgid file
  shell: "grep -i '^{{ container_run_as_group }}:.*' /etc/subgid"
  register: gid_line_found
  when: container_run_as_group != 'root'

- name: ensure user is in subuid file, if it was missing
  lineinfile:
    path: /etc/subuid
    regexp: "^{{ container_run_as_user }}:.*"
    line: "{{ container_run_as_user }}:165536:65536"
    create: true
    mode: '0644'
    owner: root
    group: root
  when: (not skip_subgid_change) and container_run_as_user != 'root' not uid_line_found.rc

- name: ensure group is in subgid file, if it was missing
  lineinfile:
    path: /etc/subgid
    regexp: "^{{ container_run_as_group }}:.*"
    line: "{{ container_run_as_group }}:165536:65536"
    create: true
    mode: '0644'
    owner: root
    group: root
  when: (not skip_subgid_change) and container_run_as_group != 'root' and gid_line_found.rc
